// AUTO-GENERATED by scripts/build-story.mjs — do not edit by hand.
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;function renderStoryTemplate(locals) {const embeddedLinguisticResources = {"verbs":{},"words":{},"adjectives":{}};var pug_html = "", protect_stack = [], pug_mixins = {}, pug_interp;;
    var locals_for_with = (locals || {});
    
    (function (JSON, Object, asksFor, console, delight, embeddedLinguisticResources, keepFrom, params, persona, quietComplaint, synHelper1, synHelper2, synHelper3, util) {
      /**
 * @license
 * Copyright 2021 Ludan Stoecklé
 * SPDX-License-Identifier: Apache-2.0
 */
//-------- allows core to communicate with the inner of the template mechanic already used by Pug (i.e. pug_html)
util.setSpy({
  getPugHtml: function () {
    return pug_html;
  },
  setPugHtml: function (new_pug_html) {
    pug_html = new_pug_html;
  },
  appendPugHtml: function (append) {
    pug_html = pug_html + append;
  },
});
util.setEmbeddedLinguisticResources(embeddedLinguisticResources);
/**
 * @license
 * Copyright 2021 Ludan Stoecklé
 * SPDX-License-Identifier: Apache-2.0
 */
//-------- using GenderNumberManager
function setRefGender(obj, gender) {
  util.genderNumberManager.setRefGender(obj, gender, null);
}
function getRefGender(obj) {
  return util.genderNumberManager.getRefGender(obj);
}
function setRefNumber(obj, number) {
  util.genderNumberManager.setRefNumber(obj, number);
}
function getRefNumber(obj) {
  return util.genderNumberManager.getRefNumber(obj);
}
function setRefGenderNumber(obj, gender, number) {
  util.genderNumberManager.setRefGenderNumber(obj, gender, number);
}
function getAnonymous(gender, number) {
  return util.genderNumberManager.getAnonymous(gender, number);
}
function getAnonMS() {
  return util.genderNumberManager.getAnonMS();
}
function getAnonMP() {
  return util.genderNumberManager.getAnonMP();
}
function getAnonFS() {
  return util.genderNumberManager.getAnonFS();
}
function getAnonFP() {
  return util.genderNumberManager.getAnonFP();
}
//-------- using RefsManager
function resetRep(obj) {
  util.refsManager.resetRep(obj);
}
function hasTriggeredRef(obj) {
  return util.refsManager.hasTriggeredRef(obj);
}
function setTriggeredRef(obj) {
  util.refsManager.setTriggeredRef(obj);
}
function dumpRefMap() {
  util.refsManager.dumpRefMap();
}
function getNextRep(obj, params) {
  return util.refsManager.getNextRep(obj, params);
}
//-------- using SaidManager
function dumpHasSaid() {
  util.saidManager.dumpHasSaid();
}
function getDumpHasSaid() {
  return util.saidManager.getDumpHasSaid();
}
function getHasSaidCopy() {
  return util.saidManager.getHasSaidCopy();
}
function recordSaid(key) {
  util.saidManager.recordSaid(key);
}
function deleteSaid(key) {
  util.saidManager.deleteSaid(key);
}
function hasSaid(key) {
  return util.saidManager.hasSaid(key);
}
function recordValue(key, value) {
  util.getSaidManager().recordValue(key, value);
}
function deleteValue(key) {
  util.getSaidManager().deleteValue(key);
}
function getValue(key) {
  return util.getSaidManager().getValue(key);
}
//-------- using helper
function hasFlag(params, flag) {
  return util.helper.hasFlag(params, flag);
}
function getFlagValue(params, flag) {
  return util.helper.getFlagValue(params, flag);
}
function protectString(string) {
  return util.helper.protectString(string);
}
function isSentenceStart() {
  return util.helper.isSentenceStart();
}
function getMorF(table, obj) {
  return util.helper.getMFN(table, obj);
}
function getMFN(table, obj) {
  return util.helper.getMFN(table, obj);
}
function getSorP(table, obj) {
  return util.helper.getSorP(table, obj);
}
//-------- using DictManager
function setWordData(word, wordData) {
  util.languageImpl.getDictManager().setWordData(word, wordData);
}
function setAdjData(word, wordData) {
  util.languageImpl.getDictManager().setAdjData(word, wordData);
}
//-------- using VerbManager
function isVerbWithPrefix(verb) {
  // only works for German
  return util.verbsManager.isVerbWithPrefix(verb);
}
/**
 * @license
 * Copyright 2021 Ludan Stoecklé
 * SPDX-License-Identifier: Apache-2.0
 */
function syn_fct(items) {
  return util.synManager.synFct(items);
}
function printObj(before, obj) {
  console.log(before + ' ' + JSON.stringify(obj).substring(0, 20));
}
function logParams(params) {
  console.log('params: ' + JSON.stringify(params));
}
function valueToSorP(val) {
  return util.languageImpl.isPlural(val) ? 'P' : 'S';
}
function debug(filename, line) {
  if (filename !== null) {
    pug_debug_filename = filename;
  }
  pug_debug_line = line;
  if (locals.renderDebug) {
    // locals is available
    let id = line;
    if (filename !== null) {
      id = filename.replace(/"/g, '') + ': ' + id;
    }
    pug_html = pug_html + `<span class="rosaenlg-debug" id="${id}"></span>`;
  }
}
pug_mixins["foreach"] = pug_interp = function(elts, mixinFct, asm, params){ // NAME_foreach
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.asmManager.foreach(elts, mixinFct, asm, params);
};
var foreach=pug_mixins["foreach"];
pug_mixins["value"] = pug_interp = function(obj, params){ // NAME_value
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.valueManager.value(obj, params);
};
var value=pug_mixins["value"];
pug_mixins["syn"] = pug_interp = function(){ // NAME_syn
var block = (this && this.block), attributes = (this && this.attributes) || {};
var items = [];
for (pug_interp = 0; pug_interp < arguments.length; pug_interp++) {
  items.push(arguments[pug_interp]);
}
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.synManager.simpleSyn(items);
};
var syn=pug_mixins["syn"];
pug_mixins["agreeAdj"] = pug_interp = function(adjective, subject, params){ // NAME_agreeAdj
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.adjectiveManager.agreeAdj(adjective, subject, params);
};
var agreeAdj=pug_mixins["agreeAdj"];
pug_mixins["recipientPossession"] = pug_interp = function(owned){ // NAME_recipientPossession
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.possessiveManager.recipientPossession(owned);
};
var recipientPossession=pug_mixins["recipientPossession"];
pug_mixins["thirdPossession"] = pug_interp = function(owner, owned, params){ // NAME_thirdPossession
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.possessiveManager.thirdPossession(owner, owned, params);
};
var thirdPossession=pug_mixins["thirdPossession"];
pug_mixins["dummy"] = pug_interp = function(){ // NAME_dummy
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
pug_mixins['dummy']();
};
var dummy=pug_mixins["dummy"];
pug_mixins["flushBuffer"] = pug_interp = function(){ // NAME_flushBuffer
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
pug_html = pug_html + "¤¤";
};
var flushBuffer=pug_mixins["flushBuffer"];
pug_mixins["eatSpace"] = pug_interp = function(){ // NAME_eatSpace
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
pug_html = pug_html + "¤EATSPACE¤";
};
var eatSpace=pug_mixins["eatSpace"];
pug_mixins["uppercaseWords"] = pug_interp = function(str){ // NAME_uppercaseWords
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
pug_html = pug_html + "¤" + (pug_escape(null == (pug_interp = util.helper.getUppercaseWords(str)) ? "" : pug_interp)) + "¤";
};
var uppercaseWords=pug_mixins["uppercaseWords"];
pug_mixins["toHtmlList"] = pug_interp = function(obj){ // NAME_toHtmlList
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
pug_html = pug_html + "\u003Cul\u003E";
// iterate obj
;(function(){
  var $$obj = obj;
  if ('number' == typeof $$obj.length) {
      for (var index = 0, $$l = $$obj.length; index < $$l; index++) {
        var val = $$obj[index];
if (val!=null && typeof(val) == "object") {
pug_html = pug_html + "\u003Cli\u003E" + "¤" + (pug_escape(null == (pug_interp = index) ? "" : pug_interp)) + "¤" + "¤: ¤";
pug_mixins["toHtmlList"](val);
pug_html = pug_html + "¤¤\u003C\u002Fli\u003E";
}
else {
pug_html = pug_html + "\u003Cli\u003E" + "¤" + (pug_escape(null == (pug_interp = index + ': ' + val) ? "" : pug_interp)) + "¤" + "\u003C\u002Fli\u003E";
}
      }
  } else {
    var $$l = 0;
    for (var index in $$obj) {
      $$l++;
      var val = $$obj[index];
if (val!=null && typeof(val) == "object") {
pug_html = pug_html + "\u003Cli\u003E" + "¤" + (pug_escape(null == (pug_interp = index) ? "" : pug_interp)) + "¤" + "¤: ¤";
pug_mixins["toHtmlList"](val);
pug_html = pug_html + "¤¤\u003C\u002Fli\u003E";
}
else {
pug_html = pug_html + "\u003Cli\u003E" + "¤" + (pug_escape(null == (pug_interp = index + ': ' + val) ? "" : pug_interp)) + "¤" + "\u003C\u002Fli\u003E";
}
    }
  }
}).call(this);
pug_html = pug_html + "\u003C\u002Ful\u003E";
};
var toHtmlList=pug_mixins["toHtmlList"];
pug_mixins["verb"] = pug_interp = function(subject, verbInfo, params){ // NAME_verb
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.sentenceManager.verb(subject, verbInfo, params);
};
var verb=pug_mixins["verb"];
pug_mixins["subjectVerb"] = pug_interp = function(subject, verbInfo, params){ // NAME_subjectVerb
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.sentenceManager.subjectVerb(subject, verbInfo, params);
};
var subjectVerb=pug_mixins["subjectVerb"];
pug_mixins["subjectVerbAdj"] = pug_interp = function(subject, verbInfo, adjective, params){ // NAME_subjectVerbAdj
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.sentenceManager.subjectVerbAdj(subject, verbInfo, adjective, params);
};
var subjectVerbAdj=pug_mixins["subjectVerbAdj"];
pug_mixins["verbPart"] = pug_interp = function(){ // NAME_verbPart
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.verbsManager.popVerbPartInBuffer();
};
var verbPart=pug_mixins["verbPart"];
pug_mixins["verbPrefix"] = pug_interp = function(){ // NAME_verbPrefix
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.verbsManager.popVerbPrefixInBuffer();
};
var verbPrefix=pug_mixins["verbPrefix"];
pug_mixins["sentence"] = pug_interp = function(params){ // NAME_sentence
var block = (this && this.block), attributes = (this && this.attributes) || {};
function addToParams(_toAdd) { return Object.assign({}, params, _toAdd); }
util.sentenceManager.sentence(params);
};
var sentence=pug_mixins["sentence"];
function has(x){ return x && (''+x).trim().length > 0; }
pug_html = pug_html + "¤This is a¤" + "¤" + (pug_escape(null == (pug_interp = ' ' + persona + ' ') ? "" : pug_interp)) + "¤" + "¤guest you know¤";
pug_mixins['synHelper1'] = pug_interp = function(pos){
  switch(pos){
case 1:
pug_html = pug_html + "¤well.¤";
  break;
case 2:
pug_html = pug_html + "¤inside out.¤";
  break;
case 3:
pug_html = pug_html + "¤on sight.¤";
  break;
  }
};
var synHelper1=pug_mixins["synHelper1"];
util.synManager.runSynz(synHelper1, 'synHelper1', 3, Object.assign({}, undefined, {}));
if (has(quietComplaint)) {
pug_html = pug_html + ("¤ What quietly bothers them:¤" + "¤" + (pug_escape(null == (pug_interp = ' ' + quietComplaint + '.') ? "" : pug_interp)) + "¤");
}
if (has(delight)) {
pug_mixins['synHelper2'] = pug_interp = function(pos){
  switch(pos){
case 1:
pug_html = pug_html + "¤ What would make their day:¤";
  break;
case 2:
pug_html = pug_html + "¤ The small thing that lands:¤";
  break;
  }
};
var synHelper2=pug_mixins["synHelper2"];
util.synManager.runSynz(synHelper2, 'synHelper2', 2, Object.assign({}, undefined, {}));
pug_html = pug_html + "¤" + (pug_escape(null == (pug_interp = ' ' + delight + '.') ? "" : pug_interp)) + "¤";
}
if (has(asksFor)) {
pug_html = pug_html + ("¤ They ask for something you don't stock¤" + "¤" + (pug_escape(null == (pug_interp = ' \u2014 ' + asksFor + '.') ? "" : pug_interp)) + "¤");
}
if (has(keepFrom)) {
pug_html = pug_html + ("¤ A room to keep them from:¤" + "¤" + (pug_escape(null == (pug_interp = ' ' + keepFrom + '.') ? "" : pug_interp)) + "¤");
}
pug_html = pug_html + "¤ The small things a system never sees¤";
pug_mixins['synHelper3'] = pug_interp = function(pos){
  switch(pos){
case 1:
pug_html = pug_html + "¤ \\u2014 but you did.¤";
  break;
case 2:
pug_html = pug_html + "¤ \\u2014 and you caught them.¤";
  break;
  }
};
var synHelper3=pug_mixins["synHelper3"];
util.synManager.runSynz(synHelper3, 'synHelper3', 2, Object.assign({}, undefined, {}));
    }.call(this, "JSON" in locals_for_with ?
        locals_for_with.JSON :
        typeof JSON !== 'undefined' ? JSON : undefined, "Object" in locals_for_with ?
        locals_for_with.Object :
        typeof Object !== 'undefined' ? Object : undefined, "asksFor" in locals_for_with ?
        locals_for_with.asksFor :
        typeof asksFor !== 'undefined' ? asksFor : undefined, "console" in locals_for_with ?
        locals_for_with.console :
        typeof console !== 'undefined' ? console : undefined, "delight" in locals_for_with ?
        locals_for_with.delight :
        typeof delight !== 'undefined' ? delight : undefined, "embeddedLinguisticResources" in locals_for_with ?
        locals_for_with.embeddedLinguisticResources :
        typeof embeddedLinguisticResources !== 'undefined' ? embeddedLinguisticResources : undefined, "keepFrom" in locals_for_with ?
        locals_for_with.keepFrom :
        typeof keepFrom !== 'undefined' ? keepFrom : undefined, "params" in locals_for_with ?
        locals_for_with.params :
        typeof params !== 'undefined' ? params : undefined, "persona" in locals_for_with ?
        locals_for_with.persona :
        typeof persona !== 'undefined' ? persona : undefined, "quietComplaint" in locals_for_with ?
        locals_for_with.quietComplaint :
        typeof quietComplaint !== 'undefined' ? quietComplaint : undefined, "synHelper1" in locals_for_with ?
        locals_for_with.synHelper1 :
        typeof synHelper1 !== 'undefined' ? synHelper1 : undefined, "synHelper2" in locals_for_with ?
        locals_for_with.synHelper2 :
        typeof synHelper2 !== 'undefined' ? synHelper2 : undefined, "synHelper3" in locals_for_with ?
        locals_for_with.synHelper3 :
        typeof synHelper3 !== 'undefined' ? synHelper3 : undefined, "util" in locals_for_with ?
        locals_for_with.util :
        typeof util !== 'undefined' ? util : undefined));
    ;;return locals.util.getFiltered();}
export default renderStoryTemplate
