// Spike: compile a RosaeNLG template to a standalone browser module.
// Run locally:  node scripts/build-story.mjs
// (best-effort — exact RosaeNLG API may need adjustment based on the error you get)
import fs from 'fs'
import rosaenlgPug from 'rosaenlg'

const OUT = 'src/lib/storyCompiled.js'

try {
  // compileFileClient → returns a JS function *string*; embedResources makes it standalone
  const compiled = rosaenlgPug.compileFileClient('src/story/guest.pug', {
    language: 'en_US',
    compileDebug: false,
    embedResources: true,
    name: 'renderStoryTemplate',
  })
  const module = `// AUTO-GENERATED by scripts/build-story.mjs — do not edit by hand.\n${compiled}\nexport default renderStoryTemplate\n`
  fs.writeFileSync(OUT, module)
  console.log('OK → wrote ' + OUT + ' (' + module.length + ' bytes)')
} catch (e) {
  console.error('COMPILE FAILED:', e && e.message ? e.message : e)
  console.error('\nPaste this whole error back so we can adjust the API call.')
  process.exit(1)
}
